export const SET_MODEL = "SET_MODEL";
export const UPDATE_MODEL = "UPDATE_MODEL";
export const SET_MODEL_SUCCESS = "SET_MODEL_SUCCESS";
export const RECOGNIZE_FEATURES = "RECOGNIZE_FEATURES";
export const RECOGNIZE_FEATURES_SUCCESS = "RECOGNIZE_FEATURES_SUCCESS";
export const RECOGNIZE_FEATURES_CANCEL = "RECOGNIZE_FEATURES_CANCEL";
export const SET_CANCEL_TOKEN_SOURCE = "SET_CANCEL_TOKEN_SOURCE";
export const RESET_CANCEL_TOKEN_SOURCE = "RESET_CANCEL_TOKEN_SOURCE";

export const GENERATE_PREVIEW_MODEL = "GENERATE_PREVIEW_MODEL";
export const PREVIEW_LOADING_DONE = "PREVIEW_LOADING_DONE";
export const LOAD_FEATURES = "LOAD_FEATURES";

export const SET_MODEL_SIZE = "SET_MODEL_SIZE";

export const SET_SELECTED_AXES = "SET_SELECTED_AXES";

export const SET_MATERIAL = "SET_MATERIAL";

export const SELECT_FEATURE = "SELECT_FEATURE";

export const TOOLS_LOADING = "TOOLS_LOADING";
export const TOOLS_LOADING_DONE = "TOOLS_LOADING_DONE";

export const RESET_MODEL_STATE = "RESET_MODEL_STATE";

export const TOGGLE_FEATURES_BY_AXIS = "TOGGLE_FEATURES_BY_AXIS";

export const TOGGLE_GROUP = "TOGGLE_GROUP";

export const UPDATE_BLANK = "UPDATE_BLANK";

export const TOGGLE_BLANK = "TOGGLE_BLANK";

export const SET_FEATURES_BY_AXES_DATA = "SET_FEATURES_BY_AXES_DATA";

export const RESET_FEATURES_BY_AXES = "RESET_FEATURES_BY_AXES";

export const LOAD_FEATURE_PARAMETER = "LOAD_FEATURE_PARAMETER";

export const SET_FEATURE_PARAMETERS = "SET_FEATURE_PARAMETERS";