import { IMaterial, ICategory, ISearchEntry } from "~/components/DefineWorkPiece/MaterialSelectionWidget/types";

export const categoryList: ICategory[] = [
    {
        ISOMaterial: "P",
        MasterText: "Steels, ferritic, martensitic and precipitation-hardening stainless steels",
        TranslationId: "bb943368-fd75-4493-aa53-9b4b1f95e00d",
    },
    {
        ISOMaterial: "M",
        MasterText: "Austenitic and duplex stainless steels",
        TranslationId: "1ca97f0f-b4cb-494d-99cd-3038323c3a29",
    },
    {
        ISOMaterial: "K",
        MasterText: "Cast irons",
        TranslationId: "831efcfc-a211-434f-896c-2571ebefaf3b",
    },
    {
        ISOMaterial: "N",
        MasterText: "Non-ferrous metals",
        TranslationId: "37fd165e-3a2a-4d55-900b-0d1cfbbd972f",
    },
    {
        ISOMaterial: "S",
        MasterText: "Superalloys and titanium",
        TranslationId: "1b7e9dd5-c38f-495e-9704-cc554f11db7c",
    },
    {
        ISOMaterial: "H",
        MasterText: "Hard materials",
        TranslationId: "86bccaed-dcbd-4323-86ed-cc9b9b249aa5",
    },
    {
        ISOMaterial: "OD",
        MasterText: "Other difficult materials",
        TranslationId: "8045ac38-4b47-4a21-8bb7-542fa073de4d",
    },
    {
        ISOMaterial: "PC",
        MasterText: "Plastics and Composites",
        TranslationId: "0aaf2f4e-adf0-439c-885e-d89003f1b2b5",
    },
    {
        ISOMaterial: "GR",
        MasterText: "Graphite",
        TranslationId: "e4ee68db-0613-49e9-af3a-b0e61e8e9dcc",
    },
];

export const materialList: IMaterial[] = [
    {
        Name: "P1",
        ISOMaterial: "P",
        MasterText: "Free-cutting steels",
        TranslationId: null,
        RefMtrl: "11 SMn30",
        RefMtrl_Nafta: "1213",
        kc11: 1500.0,
        mc: 0.14,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 385,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: 360,
        Rm_Calib_min_Imperial: 50,
        Rm_Calib_max: 880,
        Rm_Calib_max_Imperial: 130,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P2",
        ISOMaterial: "P",
        MasterText: "Low-alloy ferritic general structural steels, C < 0.25%wt",
        TranslationId: null,
        RefMtrl: "S235JRG2",
        RefMtrl_Nafta: "A573 Grade 58",
        kc11: 1600.0,
        mc: 0.23,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 420,
        Rm_nom_Imperial: 60,
        Rm_Calib_min: 320,
        Rm_Calib_min_Imperial: 45,
        Rm_Calib_max: 600,
        Rm_Calib_max_Imperial: 85,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P3",
        ISOMaterial: "P",
        MasterText: "Ferritic & ferritic/pearlitic general structural steels, C < 0.25%wt",
        TranslationId: null,
        RefMtrl: "16 MnCr 5",
        RefMtrl_Nafta: "5115",
        kc11: 1800.0,
        mc: 0.14,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 550,
        Rm_nom_Imperial: 80,
        Rm_Calib_min: 430,
        Rm_Calib_min_Imperial: 60,
        Rm_Calib_max: 610,
        Rm_Calib_max_Imperial: 90,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P4",
        ISOMaterial: "P",
        MasterText: "Low-alloy general structural steels, 0.25% < C < 0.67%wt",
        TranslationId: null,
        RefMtrl: "C 45E",
        RefMtrl_Nafta: "1045",
        kc11: 2000.0,
        mc: 0.15,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 660,
        Rm_nom_Imperial: 95,
        Rm_Calib_min: 520,
        Rm_Calib_min_Imperial: 75,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P5",
        ISOMaterial: "P",
        MasterText: "Structural steels, 0.25% < C < 0.67%wt",
        TranslationId: null,
        RefMtrl: "42 CrMo 4",
        RefMtrl_Nafta: "4140",
        kc11: 2020.0,
        mc: 0.18,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 700,
        Rm_nom_Imperial: 100,
        Rm_Calib_min: 520,
        Rm_Calib_min_Imperial: 75,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P6",
        ISOMaterial: "P",
        MasterText: "Low-alloy through-hardening steels, C > 0.67%wt",
        TranslationId: null,
        RefMtrl: "C 100S",
        RefMtrl_Nafta: "1095",
        kc11: 2100.0,
        mc: 0.17,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 600,
        Rm_nom_Imperial: 85,
        Rm_Calib_min: 520,
        Rm_Calib_min_Imperial: 75,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P7",
        ISOMaterial: "P",
        MasterText: "Through-hardening steels, C > 0.67%wt",
        TranslationId: null,
        RefMtrl: "100 Cr 6",
        RefMtrl_Nafta: "52100",
        kc11: 2160.0,
        mc: 0.17,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 650,
        Rm_nom_Imperial: 95,
        Rm_Calib_min: 600,
        Rm_Calib_min_Imperial: 85,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P8",
        ISOMaterial: "P",
        MasterText: "Tool steels & High Speed Steels (HSS)",
        TranslationId: null,
        RefMtrl: "X 40 CrMoV 5 1",
        RefMtrl_Nafta: "H13",
        kc11: 2400.0,
        mc: 0.2,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 700,
        Rm_nom_Imperial: 100,
        Rm_Calib_min: 600,
        Rm_Calib_min_Imperial: 85,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionRadialWithStock",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P11",
        ISOMaterial: "P",
        MasterText: "Ferritic & martensitic stainless steels",
        TranslationId: null,
        RefMtrl: "X 20 Cr 13",
        RefMtrl_Nafta: "420",
        kc11: 2000.0,
        mc: 0.15,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 675,
        Rm_nom_Imperial: 100,
        Rm_Calib_min: 415,
        Rm_Calib_min_Imperial: 60,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "P12",
        ISOMaterial: "P",
        MasterText: "Maraging and precipitation-hardening stainless steels",
        TranslationId: null,
        RefMtrl: "X 5 CrNiCuNb 16 4",
        RefMtrl_Nafta: "17-4 PH",
        kc11: 2100.0,
        mc: 0.17,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 1100,
        Rm_nom_Imperial: 160,
        Rm_Calib_min: 500,
        Rm_Calib_min_Imperial: 75,
        Rm_Calib_max: 1200,
        Rm_Calib_max_Imperial: 175,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "M1",
        ISOMaterial: "M",
        MasterText: "Free-cutting austenitic stainless steels",
        TranslationId: null,
        RefMtrl: "X 8 CrNiS 18 9",
        RefMtrl_Nafta: "303",
        kc11: 1700.0,
        mc: 0.14,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "M2",
        ISOMaterial: "M",
        MasterText: "Low-alloy austenitic stainless steels",
        TranslationId: null,
        RefMtrl: "X 5 CrNi 18 10",
        RefMtrl_Nafta: "304",
        kc11: 1920.0,
        mc: 0.18,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "M3",
        ISOMaterial: "M",
        MasterText: "Medium-alloy austenitic stainless steels",
        TranslationId: null,
        RefMtrl: "X 2 CrNiMo 18 14 3",
        RefMtrl_Nafta: "316L",
        kc11: 2070.0,
        mc: 0.17,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "M4",
        ISOMaterial: "M",
        MasterText: "High-alloy austenitic and duplex stainless steels",
        TranslationId: null,
        RefMtrl: "X 2 CrNiMoN 22 5 3",
        RefMtrl_Nafta: "2205 Duplex",
        kc11: 2230.0,
        mc: 0.16,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "M5",
        ISOMaterial: "M",
        MasterText: "Difficult high-alloy austenitic and duplex stainless steels",
        TranslationId: null,
        RefMtrl: "X 2 CrNiMoN 25 7 4",
        RefMtrl_Nafta: "2507 Super duplex",
        kc11: 2510.0,
        mc: 0.13,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K1",
        ISOMaterial: "K",
        MasterText: "Grey cast irons (GCI)",
        TranslationId: null,
        RefMtrl: "EN-GJL-250",
        RefMtrl_Nafta: "A48 35 B",
        kc11: 930.0,
        mc: 0.32,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K2",
        ISOMaterial: "K",
        MasterText: "Compacted graphite irons (CGI)",
        TranslationId: null,
        RefMtrl: "EN-GJV-400",
        RefMtrl_Nafta: "Grade 400-15",
        kc11: 1000.0,
        mc: 0.35,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K3",
        ISOMaterial: "K",
        MasterText: "Malleable cast irons (MCI)",
        TranslationId: null,
        RefMtrl: "EN-GJMB-550-4",
        RefMtrl_Nafta: "A220 60004",
        kc11: 1050.0,
        mc: 0.37,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K4",
        ISOMaterial: "K",
        MasterText: "Nodular cast irons (SGI)",
        TranslationId: null,
        RefMtrl: "EN-GJS-500-7",
        RefMtrl_Nafta: "A536 80-55-06",
        kc11: 1160.0,
        mc: 0.37,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialTwoThirdsOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K5",
        ISOMaterial: "K",
        MasterText: "Austempered ductile irons (ADI)",
        TranslationId: null,
        RefMtrl: "EN-GJS-1000-5",
        RefMtrl_Nafta: "1050/700/7",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialTwoThirdsOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K6",
        ISOMaterial: "K",
        MasterText: "Austenitic lamellar cast irons",
        TranslationId: null,
        RefMtrl: "EN-GJLA-XNiCuCr15-6-2",
        RefMtrl_Nafta: "A436 Type 1 (Ni-Resist 1)",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "K7",
        ISOMaterial: "K",
        MasterText: "Austenitic nodular cast irons",
        TranslationId: null,
        RefMtrl: "EN-GJSA-XNiMn23-4",
        RefMtrl_Nafta: "A439 Type D-2M (Ni-Resist D-2M)",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "N1",
        ISOMaterial: "N",
        MasterText: "Aluminium alloys, Si < 9%",
        TranslationId: null,
        RefMtrl: "AW-7075",
        RefMtrl_Nafta: "AA7075-T6",
        kc11: 650.0,
        mc: 0.25,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "N2",
        ISOMaterial: "N",
        MasterText: "Aluminium alloys, 9% < Si < 16%",
        TranslationId: null,
        RefMtrl: "AC-44200\\nSi = 12%",
        RefMtrl_Nafta: "A413.2",
        kc11: 700.0,
        mc: 0.25,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "N3",
        ISOMaterial: "N",
        MasterText: "Aluminium alloys, Si >16%",
        TranslationId: null,
        RefMtrl: "AlSi17Cu5",
        RefMtrl_Nafta: "AlSi17Cu5",
        kc11: 720.0,
        mc: 0.25,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "N11",
        ISOMaterial: "N",
        MasterText: "Copper alloys",
        TranslationId: null,
        RefMtrl: "CW614N",
        RefMtrl_Nafta: "C38500",
        kc11: 740.0,
        mc: 0.26,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionSingleCut",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "S1",
        ISOMaterial: "S",
        MasterText: "Iron-based superalloys",
        TranslationId: null,
        RefMtrl: "Discalloy",
        RefMtrl_Nafta: "Discalloy",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "S2",
        ISOMaterial: "S",
        MasterText: "Cobalt-based superalloys",
        TranslationId: null,
        RefMtrl: "Stellite 21",
        RefMtrl_Nafta: "Stellite 21",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "S3",
        ISOMaterial: "S",
        MasterText: "Nickel-based superalloys",
        TranslationId: null,
        RefMtrl: "Inconel 718",
        RefMtrl_Nafta: "Inconel 718",
        kc11: 2530.0,
        mc: 0.21,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "S11",
        ISOMaterial: "S",
        MasterText: "Titanium, low alloyed, (α)",
        TranslationId: null,
        RefMtrl: "Ti",
        RefMtrl_Nafta: "Ti",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "S12",
        ISOMaterial: "S",
        MasterText: "Titanium, medium alloyed, (α+β)",
        TranslationId: null,
        RefMtrl: "TiAl6V4",
        RefMtrl_Nafta: "TiAl6V4",
        kc11: 1500.0,
        mc: 0.24,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "S13",
        ISOMaterial: "S",
        MasterText: "Titanium, high alloyed, (near β and β)",
        TranslationId: null,
        RefMtrl: "Ti10V2Fe3Al",
        RefMtrl_Nafta: "Ti10V2Fe3Al",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H3",
        ISOMaterial: "H",
        MasterText: "Case-hardened steels",
        TranslationId: null,
        RefMtrl: "16 MnCr 5",
        RefMtrl_Nafta: "5115",
        kc11: 2070.0,
        mc: 0.14,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 60,
        HRC_Calib_min: 58,
        HRC_Calib_max: 62,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H5",
        ISOMaterial: "H",
        MasterText: "Quenched & Tempered steels",
        TranslationId: null,
        RefMtrl: "42 CrMo 4",
        RefMtrl_Nafta: "4140",
        kc11: 2320.0,
        mc: 0.18,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 50,
        HRC_Calib_min: 38,
        HRC_Calib_max: 56,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H7",
        ISOMaterial: "H",
        MasterText: "Quenched & Tempered steels, Bearing steels",
        TranslationId: null,
        RefMtrl: "100 Cr 6",
        RefMtrl_Nafta: "52100",
        kc11: 2480.0,
        mc: 0.17,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 60,
        HRC_Calib_min: 56,
        HRC_Calib_max: 64,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H8",
        ISOMaterial: "H",
        MasterText: "Tool steels & High Speed Steels (HSS)",
        TranslationId: null,
        RefMtrl: "X 40 CrMoV 5 1",
        RefMtrl_Nafta: "H13",
        kc11: 2750.0,
        mc: 0.2,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 50,
        HRC_Calib_min: 38,
        HRC_Calib_max: 64,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H11",
        ISOMaterial: "H",
        MasterText: "Martensitic stainless steels",
        TranslationId: null,
        RefMtrl: "X 20 Cr 13",
        RefMtrl_Nafta: "420",
        kc11: 2300.0,
        mc: 0.15,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 45,
        HRC_Calib_min: 38,
        HRC_Calib_max: 50,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H12",
        ISOMaterial: "H",
        MasterText: "Maraged and precipitation-hardened stainless steels",
        TranslationId: null,
        RefMtrl: "X 5 CrNiCuNb 16 4",
        RefMtrl_Nafta: "17-4 PH",
        kc11: 2410.0,
        mc: 0.17,
        SF_k1: 0.0,
        CalibType: "Rm",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 1450,
        Rm_nom_Imperial: 210,
        Rm_Calib_min: 1200,
        Rm_Calib_min_Imperial: 175,
        Rm_Calib_max: 1650,
        Rm_Calib_max_Imperial: 240,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H21",
        ISOMaterial: "H",
        MasterText: "Manganese steels",
        TranslationId: null,
        RefMtrl: "X 120 Mn 12",
        RefMtrl_Nafta: "Hadfield, High manganese steel",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 50,
        HRC_Calib_min: 23,
        HRC_Calib_max: 64,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "H31",
        ISOMaterial: "H",
        MasterText: "White cast irons",
        TranslationId: null,
        RefMtrl: "EN-GJN-HV600(XCr11)",
        RefMtrl_Nafta: "A532 ID",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "HRC",
        HRC_nom: 55,
        HRC_Calib_min: 50,
        HRC_Calib_max: 64,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: "CutDivisionRadialOneThirdOneThirdOneThird",
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "PM1",
        ISOMaterial: "OD",
        MasterText: "Low-alloy PM-materials",
        TranslationId: null,
        RefMtrl: "F-0008 Fe-0.7C",
        RefMtrl_Nafta: "F-0008 Fe-0.7C",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "PM2",
        ISOMaterial: "OD",
        MasterText: "Medium-alloy PM-materials",
        TranslationId: null,
        RefMtrl: "FLC-4608 Fe2Cu1.8Ni0.5Mo0.2Mn0.8C",
        RefMtrl_Nafta: "FLC-4608 Fe2Cu1.8Ni0.5Mo0.2Mn0.8C",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "PM3",
        ISOMaterial: "OD",
        MasterText: "High-alloy PM-materials, exhaust valve seat materials, etc.",
        TranslationId: null,
        RefMtrl: null,
        RefMtrl_Nafta: null,
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "HF1",
        ISOMaterial: "OD",
        MasterText: "Hardfacing alloys, welded or plasma-deposited iron-based alloys",
        TranslationId: null,
        RefMtrl: null,
        RefMtrl_Nafta: null,
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "HF2",
        ISOMaterial: "OD",
        MasterText: "Hardfacing alloys, welded or plasma-deposited cobalt- and nickel-based alloys",
        TranslationId: null,
        RefMtrl: null,
        RefMtrl_Nafta: null,
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "CC1",
        ISOMaterial: "OD",
        MasterText: "Sintered tungsten carbide",
        TranslationId: null,
        RefMtrl: "G50",
        RefMtrl_Nafta: "G50",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TS1",
        ISOMaterial: "PC",
        MasterText: "Thermosetting polymers",
        TranslationId: null,
        RefMtrl: "Urea formaldehyde (UF)",
        RefMtrl_Nafta: "Urea formaldehyde (UF)",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TS2",
        ISOMaterial: "PC",
        MasterText: "Thermosetting carbon-fibre composites",
        TranslationId: null,
        RefMtrl: "T300 T700 T800 HTA-S IMA - Epoxy (M21)...",
        RefMtrl_Nafta: "T300 T700 T800 HTA-S IMA - Epoxy (M21)...",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TS3",
        ISOMaterial: "PC",
        MasterText: "Thermosetting glass-fibre composites",
        TranslationId: null,
        RefMtrl: "Epoxy - HX..(42..)/E glass (7781...)...",
        RefMtrl_Nafta: "Epoxy - HX..(42..)/E glass (7781...)...",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TS4",
        ISOMaterial: "PC",
        MasterText: "Thermosetting aramide-fibre composites",
        TranslationId: null,
        RefMtrl: "Kevlar 49",
        RefMtrl_Nafta: "Kevlar 49",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TP1",
        ISOMaterial: "PC",
        MasterText: "Thermoplastic polymers",
        TranslationId: null,
        RefMtrl: "Polycarbonate (PC)",
        RefMtrl_Nafta: "Polycarbonate (PC)",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TP2",
        ISOMaterial: "PC",
        MasterText: "Thermoplastic carbon-fibre composites",
        TranslationId: null,
        RefMtrl: "PPS/PEEK - T300..",
        RefMtrl_Nafta: "PPS/PEEK - T300..",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TP3",
        ISOMaterial: "PC",
        MasterText: "Thermoplastic glass-fibre composites",
        TranslationId: null,
        RefMtrl: "PPS/PEEK - E glass or A glass...",
        RefMtrl_Nafta: "PPS/PEEK - E glass or A glass...",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "TP4",
        ISOMaterial: "PC",
        MasterText: "Thermoplastic aramide-fibre composites",
        TranslationId: null,
        RefMtrl: null,
        RefMtrl_Nafta: null,
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
    {
        Name: "GR1",
        ISOMaterial: "GR",
        MasterText: "Graphite",
        TranslationId: null,
        RefMtrl: "R 8500",
        RefMtrl_Nafta: "R 8500",
        kc11: 0.0,
        mc: 0.0,
        SF_k1: 0.0,
        CalibType: "None",
        HRC_nom: 0,
        HRC_Calib_min: 0,
        HRC_Calib_max: 0,
        Rm_nom: 0,
        Rm_nom_Imperial: 0,
        Rm_Calib_min: 0,
        Rm_Calib_min_Imperial: 0,
        Rm_Calib_max: 0,
        Rm_Calib_max_Imperial: 0,
        ThreadMill_RadInf: null,
        IsFavorite: false,
        Calibration: 0,
    },
];

export const searchList: ISearchEntry[] = [
    {
        GUID: "de414cea-be6e-40cc-9553-5f4b60a4dc3c",
        Name: "(318)",
        Std: "AISI / ASTM",
        Std_DIN: null,
        SMG: "M4",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Duplex",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 700,
        Rm_nom_Imperial: 100,
        Rm_Calib_min: 660,
        Rm_Calib_min_Imperial: 95,
        Rm_Calib_max: 860,
        Rm_Calib_max_Imperial: 125,
        Calibration: 0,
    },
    {
        GUID: "f73228d8-888a-4eba-b6c3-ca666113d414",
        Name: "(CuZn38Pb2)",
        Std: "AFNOR",
        Std_DIN: "CuZn38Pb1.5",
        SMG: "N11",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: null,
        Rm_nom_Imperial: null,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "66be95b5-25b0-4c66-b15f-1948705de8f4",
        Name: "(H2211-92)",
        Std: "JIS",
        Std_DIN: null,
        SMG: "N1",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 310,
        Rm_nom_Imperial: 45,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "03df4a5f-a02c-40d2-a6f9-cdde025a8bd2",
        Name: "(T51604)",
        Std: "UNS",
        Std_DIN: "X 6 CrMo 4",
        SMG: "P8",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: null,
        Rm_nom_Imperial: null,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "d7e66f20-6d10-43ac-b212-8a416a5e2588",
        Name: "0.6250",
        Std: "EN-Nr",
        Std_DIN: "GG-25",
        SMG: "K1",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Grey cast iron (GCI)",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: null,
        Rm_nom_Imperial: null,
        Rm_Calib_min: 250,
        Rm_Calib_min_Imperial: 35,
        Rm_Calib_max: 350,
        Rm_Calib_max_Imperial: 50,
        Calibration: 0,
    },
    {
        GUID: "3a0cd48d-ed9d-4964-ad39-ff965e21bf1e",
        Name: "0.6655",
        Std: "EN-Nr",
        Std_DIN: "GGL-NiCuCr 15 6 2",
        SMG: "K6",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic lamellar cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 170,
        Rm_nom_Imperial: 25,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "e41a8de8-1411-4757-90f2-7c5b88b37297",
        Name: "0.6661",
        Std: "EN-Nr",
        Std_DIN: "GGL-NiCr 20 3",
        SMG: "K6",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic lamellar cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 190,
        Rm_nom_Imperial: 30,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "17eedc38-6498-4a1c-90d9-7bd98515b919",
        Name: "0.6667",
        Std: "W.-Nr",
        Std_DIN: "GGL-NiSiCr 20 5 3",
        SMG: "K6",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic lamellar cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 380,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "9f5ad9ed-c37b-4e90-bc0d-f7edfd59b020",
        Name: "0.6680",
        Std: "W.-Nr",
        Std_DIN: "GGL-NiSiCr 30 5 5",
        SMG: "K6",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic lamellar cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 390,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "addcc794-008b-48e7-8ee5-41cb40643a38",
        Name: "0.7070",
        Std: "EN-Nr",
        Std_DIN: "GGG-70",
        SMG: "K4",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Nodular cast iron (SGI)",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 700,
        Rm_nom_Imperial: 100,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "6e4ef7a3-f699-4b73-b17d-3d2f1091fa79",
        Name: "0.7660",
        Std: "EN-Nr",
        Std_DIN: "GGG-NiCr 20 2",
        SMG: "K7",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic nodular cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 380,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "89afa3d0-55fb-467e-bc90-bd2049308c16",
        Name: "0.7670",
        Std: "W.-Nr",
        Std_DIN: "GGG-Ni 22",
        SMG: "K7",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic nodular cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 370,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "60f3c690-b47c-4338-8fae-1ed259bf4dac",
        Name: "0.7677",
        Std: "W.-Nr",
        Std_DIN: "GGG-NiCr 30 1",
        SMG: "K7",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic nodular cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 380,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "32261c15-0efd-4cea-bcad-77c2412884bd",
        Name: "0.8135",
        Std: "EN-Nr",
        Std_DIN: "GTS-35-10",
        SMG: "K3",
        Condition: "Tempered",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Malleable cast iron (MCI)",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 350,
        Rm_nom_Imperial: 50,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "17ad0bc5-daff-4d35-954b-9a72e5e99b32",
        Name: "03Х22Н5АМ2",
        Std: "ГОСТ",
        Std_DIN: null,
        SMG: "M3",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 515,
        Rm_nom_Imperial: 75,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "038ff601-f74a-480f-a1db-38dbed800723",
        Name: "04 66-00",
        Std: "SS",
        Std_DIN: "G-X260 Cr 27",
        SMG: "H31",
        Condition: null,
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "White cast iron",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: 55,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: null,
        Rm_nom_Imperial: null,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "4e8a2a27-6084-49cf-9dd2-48988579069f",
        Name: "040 A 22",
        Std: "BS",
        Std_DIN: "Ck 22",
        SMG: "P2",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 420,
        Rm_nom_Imperial: 60,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "dc0a1afc-5993-4aab-b8e2-235fa10c2824",
        Name: "060 A 96",
        Std: "BS",
        Std_DIN: "Ck 101",
        SMG: "H5",
        Condition: "Quenched & Tempered",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: 62,
        HRC_Calib_min: 40,
        HRC_Calib_max: 66,
        Rm_nom: null,
        Rm_nom_Imperial: null,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "7ec4f1b3-f6de-46ea-ba75-066f68e8f657",
        Name: "06KHN28MDT",
        Std: "GOST",
        Std_DIN: "X 1 NiCrMoCuN 31 27 4",
        SMG: "M5",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 650,
        Rm_nom_Imperial: 95,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "2318e62b-fd9f-4459-a60d-ae0b21903055",
        Name: "070 M 26",
        Std: "BS",
        Std_DIN: "C 25",
        SMG: "P2",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 440,
        Rm_nom_Imperial: 65,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "1083f030-5a67-415e-8e57-61cce073e547",
        Name: "080 A 62",
        Std: "BS",
        Std_DIN: "C 60",
        SMG: "P4",
        Condition: "Normalized",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 670,
        Rm_nom_Imperial: 95,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "800e3990-0266-4bc3-a05a-6d53943adcdb",
        Name: "08KH17N5M3",
        Std: "GOST",
        Std_DIN: null,
        SMG: "P12",
        Condition: "Solution annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Austenitic/Ferritic",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 1105,
        Rm_nom_Imperial: 160,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "f9b069a2-d569-4712-a0ab-de6fa62276c1",
        Name: "1.0214",
        Std: "EN-Nr",
        Std_DIN: null,
        SMG: "P2",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Ferrite",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 400,
        Rm_nom_Imperial: 60,
        Rm_Calib_min: 360,
        Rm_Calib_min_Imperial: 50,
        Rm_Calib_max: 470,
        Rm_Calib_max_Imperial: 70,
        Calibration: 0,
    },
    {
        GUID: "730de0bf-5947-4656-9409-b72448b5068a",
        Name: "1.0303",
        Std: "EN-Nr",
        Std_DIN: "St 32-3",
        SMG: "P2",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: "Ferrite",
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 380,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: 320,
        Rm_Calib_min_Imperial: 45,
        Rm_Calib_max: 470,
        Rm_Calib_max_Imperial: 70,
        Calibration: 0,
    },
    {
        GUID: "20156467-0f31-4de9-854f-b72128135569",
        Name: "1.0718",
        Std: "W.-Nr",
        Std_DIN: "9 SMnPb 28",
        SMG: "P1",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 385,
        Rm_nom_Imperial: 55,
        Rm_Calib_min: 360,
        Rm_Calib_min_Imperial: 50,
        Rm_Calib_max: 630,
        Rm_Calib_max_Imperial: 90,
        Calibration: 0,
    },
    {
        GUID: "40fd4e65-dec4-4c72-a558-466ac642da0c",
        Name: "1.0726",
        Std: "EN-Nr",
        Std_DIN: "35 S 20",
        SMG: "P1",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 540,
        Rm_nom_Imperial: 80,
        Rm_Calib_min: 470,
        Rm_Calib_min_Imperial: 70,
        Rm_Calib_max: 630,
        Rm_Calib_max_Imperial: 90,
        Calibration: 0,
    },
    {
        GUID: "21f1fccf-6be3-4971-8929-7827d381a1cc",
        Name: "1.1121",
        Std: "W.-Nr",
        Std_DIN: "Ck 10",
        SMG: "P2",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 430,
        Rm_nom_Imperial: 60,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "87b6aa8f-6061-4a39-8839-435d64d945d6",
        Name: "1.1158",
        Std: "W.-Nr",
        Std_DIN: "Ck 25",
        SMG: "P2",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 440,
        Rm_nom_Imperial: 65,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "c5c36c6b-7017-4a95-966e-43ad814099e2",
        Name: "1.1191",
        Std: "W.-Nr",
        Std_DIN: "Ck 45",
        SMG: "P4",
        Condition: null,
        ConditionTranslationId: null,
        Form: "cold drawn",
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 625,
        Rm_nom_Imperial: 90,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "7c3eabbb-eaf3-42f8-a350-4f2abb07cc7c",
        Name: "1.1231",
        Std: "W.-Nr",
        Std_DIN: "Ck 67",
        SMG: "H5",
        Condition: "Quenched & Tempered",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: 50,
        HRC_Calib_min: 45,
        HRC_Calib_max: 67,
        Rm_nom: null,
        Rm_nom_Imperial: null,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    {
        GUID: "1256ecf3-a19f-44c8-a359-fa1cdc9f3229",
        Name: "1.1231",
        Std: "W.-Nr",
        Std_DIN: "Ck 67",
        SMG: "P6",
        Condition: "Annealed",
        ConditionTranslationId: null,
        Form: null,
        FormTranslationId: null,
        Structure: null,
        StructureTranslationId: null,
        IsFavorite: false,
        HRC_nom: null,
        HRC_Calib_min: null,
        HRC_Calib_max: null,
        Rm_nom: 640,
        Rm_nom_Imperial: 95,
        Rm_Calib_min: null,
        Rm_Calib_min_Imperial: null,
        Rm_Calib_max: null,
        Rm_Calib_max_Imperial: null,
        Calibration: 0,
    },
    /*
  {
      "GUID": "970a3651-e606-4bfd-a3f1-858e34df21d2",
      "Name": "1.1274",
      "Std": "EN-Nr",
      "Std_DIN": "Ck 101",
      "SMG": "P6",
      "Condition": null,
      "ConditionTranslationId": null,
      "Form": "cold drawn",
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": 685,
      "Rm_nom_Imperial": 100,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "0a243806-647d-4f36-8ee2-bd7ed9908a70",
      "Name": "1.1520",
      "Std": "W.-Nr",
      "Std_DIN": "C 70 W1",
      "SMG": "P6",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": 650,
      "Rm_nom_Imperial": 95,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "4ea5b9bb-ce83-4937-958e-ff9de05041ed",
      "Name": "1.1525",
      "Std": "W.-Nr",
      "Std_DIN": "C 80 W1",
      "SMG": "H5",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 60,
      "HRC_Calib_min": 42,
      "HRC_Calib_max": 67,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "f2fe930b-d701-4263-9966-121e363c7ca3",
      "Name": "1.1620",
      "Std": "W.-Nr",
      "Std_DIN": "C 70 W2",
      "SMG": "H5",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 60,
      "HRC_Calib_min": 41,
      "HRC_Calib_max": 66,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "d68b6be3-29e6-4b55-a0a2-86991f457cd6",
      "Name": "1.1625",
      "Std": "W.-Nr",
      "Std_DIN": "C 80 W2",
      "SMG": "H5",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 60,
      "HRC_Calib_min": 42,
      "HRC_Calib_max": 67,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "797104a2-2d34-48cd-9232-fe86530de336",
      "Name": "1.1645",
      "Std": "W.-Nr",
      "Std_DIN": "C 105 W2",
      "SMG": "P6",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": 750,
      "Rm_nom_Imperial": 110,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "1686d254-979f-421b-95ac-594e831a84a9",
      "Name": "1.1750",
      "Std": "W.-Nr",
      "Std_DIN": "C 75 W",
      "SMG": "H5",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 60,
      "HRC_Calib_min": 41,
      "HRC_Calib_max": 66,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "62ebe059-5104-4850-8f55-3d49ca759d87",
      "Name": "1.1820",
      "Std": "W.-Nr",
      "Std_DIN": "C 55 W",
      "SMG": "P4",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": 580,
      "Rm_nom_Imperial": 85,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "2eee4443-b7c1-46af-9e56-3b72cb630b1b",
      "Name": "1.2080",
      "Std": "W.-Nr",
      "Std_DIN": "X 210 Cr 12",
      "SMG": "P8",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "cac4f9b2-2181-4fff-a6d4-5049d2de512b",
      "Name": "1.2080",
      "Std": "EN-Nr",
      "Std_DIN": "X 210 Cr 12",
      "SMG": "H8",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 60,
      "HRC_Calib_min": 58,
      "HRC_Calib_max": 67,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "8efa46fe-e6f4-4ccb-a476-f1969c50d2e4",
      "Name": "1.2083",
      "Std": "EN-Nr",
      "Std_DIN": "X 42 Cr 13",
      "SMG": "P11",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "a548529a-80b9-4b11-baf4-a499c404193a",
      "Name": "1.2101",
      "Std": "W.-Nr",
      "Std_DIN": "62 SiMnCr 4",
      "SMG": "P5",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "86a61600-cb35-41b4-af44-e5f34a361a9e",
      "Name": "1.2201",
      "Std": "W.-Nr",
      "Std_DIN": "G-X 165 CrV 12",
      "SMG": "P8",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "0c0e72ef-04ca-457b-990a-4ab1d735a7a8",
      "Name": "1.2311",
      "Std": "W.-Nr",
      "Std_DIN": "40 CrMnMo 7",
      "SMG": "P5",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": 1000,
      "Rm_nom_Imperial": 145,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "ecc0bd1d-f766-4f9a-9523-cadbed692438",
      "Name": "1.2341",
      "Std": "EN-Nr",
      "Std_DIN": "X 6 CrMo 4",
      "SMG": "H3",
      "Condition": "Case hardened",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 58,
      "HRC_Calib_min": 55,
      "HRC_Calib_max": 60,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "24a4638c-34e5-4283-92d5-cd9ef3843ada",
      "Name": "1.2367",
      "Std": "W.-Nr",
      "Std_DIN": "X 38 CrMoV 5 3",
      "SMG": "P8",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "0474656b-bb80-4232-a37c-44a5255e4cfe",
      "Name": "1.2367",
      "Std": "W.-Nr",
      "Std_DIN": "X 38 CrMoV 5 3",
      "SMG": "H8",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 45,
      "HRC_Calib_min": 36,
      "HRC_Calib_max": 57,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "46a526b5-6ac3-48cb-9efd-2862b7db561c",
      "Name": "1.2369",
      "Std": "W.-Nr",
      "Std_DIN": "81 CrMoV 42 16",
      "SMG": "P8",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "a9a4038c-9668-4ed4-ad11-a94029e68952",
      "Name": "1.2369",
      "Std": "W.-Nr",
      "Std_DIN": "81 CrMoV 42 16",
      "SMG": "H8",
      "Condition": "Quenched & Tempered",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": 62,
      "HRC_Calib_min": 61,
      "HRC_Calib_max": 65,
      "Rm_nom": null,
      "Rm_nom_Imperial": null,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  },
  {
      "GUID": "38b5957d-ecd8-4df0-89f2-aa5374b061c3",
      "Name": "1.2419",
      "Std": "W.-Nr",
      "Std_DIN": "105 WCr 6",
      "SMG": "P7",
      "Condition": "Annealed",
      "ConditionTranslationId": null,
      "Form": null,
      "FormTranslationId": null,
      "Structure": null,
      "StructureTranslationId": null,
      "IsFavorite": false,
      "HRC_nom": null,
      "HRC_Calib_min": null,
      "HRC_Calib_max": null,
      "Rm_nom": 840,
      "Rm_nom_Imperial": 120,
      "Rm_Calib_min": null,
      "Rm_Calib_min_Imperial": null,
      "Rm_Calib_max": null,
      "Rm_Calib_max_Imperial": null,
      "Calibration": 0
  }
  */
];


